version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            APP_ENV: ${APP_ENV:-dev}
            APP_SECRET: ${APP_SECRET:-ChangeMe}
            DATABASE_URL: ${DATABASE_URL}
        expose:
            - "9000"  # PHP-FPM pour Nginx en local & Traefik en prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME:-symfony}.rule=Host(`${DOMAIN_NAME}`)"
            - "traefik.http.routers.${PROJECT_NAME:-symfony}.entrypoints=websecure"
            - "traefik.http.routers.${PROJECT_NAME:-symfony}.tls.certresolver=letsencrypt"
            - "traefik.http.services.${PROJECT_NAME:-symfony}.loadbalancer.server.port=9000"
    
   
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "8092:80"
    
    database:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_USER: ${POSTGRES_USER:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
        volumes:
            - database_data:/var/lib/postgresql/data

volumes:
    database_data:
